#ifndef SYSTEM_PINMUX_FEATURES_INCLUDED
#define SYSTEM_PINMUX_FEATURES_INCLUDED

#define FEATURE_SYSTEM_PINMUX_SLEWRATE_LIMITER
#define FEATURE_SYSTEM_PINMUX_DRIVE_STRENGTH
#define FEATURE_SYSTEM_PINMUX_OPEN_DRAIN

#include "pinmux.h"
#include "pinmux_public.h"

#endif
