/* This file is automatically generated and contains information from the
 * ASF.
 */
/* Current version of the ASF */
var asf_version = "$ASF_VERSION$";
/* Application note descriptors */
var asf_application_notes = [
{'name': "Atmel AVR4960: USB Host Android Accessory", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc42003.pdf", 'id_regexpr': "(common.services.usb.*host.*android.*)"},
{'name': "Atmel AVR4950: ASF - USB Host Stack", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc8486.pdf", 'id_regexpr': "(common.services.usb.*host.*)"},
{'name': "Atmel AVR4921: ASF - USB Device Stack Differences between ASF V1 and V2", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc8411.pdf", 'id_regexpr': "(common.services.usb.*device.*|avr32.services.usb._asf_v1.*)"},
{'name': "Atmel AVR32760: AVR32 UC3 USB DFU Bootloader Protocol", 'link': "http://www.atmel.com/Images/doc32131.pdf", 'id_regexpr': "(common.services.usb.*device.*dfu_atmel.*)"},
{'name': "Atmel AVR1916: USB DFU Boot Loader for XMEGA", 'link': "http://www.atmel.com/Images/doc8429.pdf", 'id_regexpr': "(common.services.usb.*device.*dfu_atmel.*)"},
{'name': "Atmel AVR4023: FLIP USB DFU Protocol", 'link': "http://www.atmel.com/Images/doc8457.pdf", 'id_regexpr': "(common.services.usb.*device.*dfu_atmel.*)"},
{'name': "Atmel AVR4920: ASF - USB Device Stack - Compliance and Performance Figures", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc8410.pdf", 'id_regexpr': "(common.services.usb.*device.*)"},
{'name': "Atmel AVR4907: ASF - USB Device CDC Application", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc8447.pdf", 'id_regexpr': "(common.services.usb.*device.*cdc.*)"},
{'name': "Atmel AVR4905: ASF - USB Device HID Generic Application", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc8499.pdf", 'id_regexpr': "(common.services.usb.*device.*hid_generic.*)"},
{'name': "Atmel AVR4904: ASF - USB Device HID Keyboard Application", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc8446.pdf", 'id_regexpr': "(common.services.usb.*device.*hid_keyboard.*)"},
{'name': "Atmel AVR4903: ASF - USB Device HID Mouse Application", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc8409.pdf", 'id_regexpr': "(common.services.usb.*device.*hid.*mouse.*)"},
{'name': "Atmel AVR4902: ASF - USB Composite Device", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc8445.pdf", 'id_regexpr': "(common.services.usb.*device.*composite.*)"},
{'name': "Atmel AVR4901: ASF - USB Device Vendor Class Application", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc8481.pdf", 'id_regexpr': "(common.services.usb.*device.*vendor.*)"},
{'name': "Atmel AVR4900: ASF - USB Device Stack", 'link': "http://www.atmel.com/dyn/resources/prod_documents/doc8360.pdf", 'id_regexpr': "(common.services.usb.*device.*)"}
];
/* Object representative of the MCUs architecture */
var asf_mcu_arch = $ASF_MCU_ARCH$;
/* Translation table from arch name to a nice displayable title */
var asf_arch_to_title = $ASF_ARCH_TITLE$;
/* ASF content */
var asf_content = $ASF_CONTENTS$;
